export const ABI: any = {
  KALDI: {
    address: "0xa4D5d167a8B1bCE4367BA607B2d012CEF7F93595",
    coinAdress: "0xa1b0fd90c6Cb69640b6a4d211FA2Bece2543e105",
    abi: [
      {
        inputs: [
          { internalType: "address", name: "_tokenAddress", type: "address" },
          { internalType: "address", name: "_treasuryWallet", type: "address" },
          { internalType: "uint256", name: "_capAmount", type: "uint256" },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
      },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "staker", type: "address" },
          { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "GetReward",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
          { indexed: true, internalType: "address", name: "newOwner", type: "address" },
        ],
        name: "OwnershipTransferred",
        type: "event",
      },
      { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Paused", type: "event" },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "tokenAddress", type: "address" },
          { indexed: false, internalType: "uint256", name: "recoverAmount", type: "uint256" },
        ],
        name: "Recovered",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "admin", type: "address" },
          { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "RewardAdded",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "staker", type: "address" },
          { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "Staked",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "admin", type: "address" },
          { indexed: false, internalType: "uint256", name: "capAmount", type: "uint256" },
        ],
        name: "StakingCap",
        type: "event",
      },
      { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Unpaused", type: "event" },
      {
        anonymous: false,
        inputs: [
          { indexed: false, internalType: "address", name: "staker", type: "address" },
          { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
          { indexed: false, internalType: "bool", name: "rewardPaid", type: "bool" },
        ],
        name: "Unstaked",
        type: "event",
      },
      { inputs: [], name: "DENOMINATOR", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "REWARD_PENALTY_PERCENTAGE", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "REWARD_PERCENTAGE", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_capAmount", type: "uint256" }], name: "StakingCapLimitAdd", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_capAmount", type: "uint256" }], name: "StakingCapLimitSub", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "TIER_DURATION", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "TREASURY_WALLET", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "UNSTAKE_PENALTY_PERCENTAGE", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_rewardAmount", type: "uint256" }], name: "addReward", outputs: [], stateMutability: "nonpayable", type: "function" },
      {
        inputs: [
          { internalType: "address", name: "_address", type: "address" },
          { internalType: "uint256", name: "_index", type: "uint256" },
        ],
        name: "earned",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      { inputs: [{ internalType: "uint256", name: "_index", type: "uint256" }], name: "getReward", outputs: [], stateMutability: "nonpayable", type: "function" },
      {
        inputs: [{ internalType: "address", name: "_staker", type: "address" }],
        name: "getUserAllStakes",
        outputs: [
          {
            components: [
              { internalType: "uint256", name: "stakeAmount", type: "uint256" },
              { internalType: "uint256", name: "startTime", type: "uint256" },
              { internalType: "uint256", name: "reward", type: "uint256" },
              { internalType: "bool", name: "isPaid", type: "bool" },
            ],
            internalType: "struct KaldiStaking.Stakes[]",
            name: "",
            type: "tuple[]",
          },
        ],
        stateMutability: "view",
        type: "function",
      },
      { inputs: [], name: "kaldiToken", outputs: [{ internalType: "contract IERC20", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_tokenAmount", type: "uint256" }], name: "recoverERC20", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "rewardAvailable", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "rewardPenaltyShare", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }], name: "stake", outputs: [], stateMutability: "nonpayable", type: "function" },
      {
        inputs: [
          { internalType: "address", name: "", type: "address" },
          { internalType: "uint256", name: "", type: "uint256" },
        ],
        name: "stakes",
        outputs: [
          { internalType: "uint256", name: "stakeAmount", type: "uint256" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "reward", type: "uint256" },
          { internalType: "bool", name: "isPaid", type: "bool" },
        ],
        stateMutability: "view",
        type: "function",
      },
      { inputs: [], name: "stakingCap", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [], name: "totalStaked", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
      { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [{ internalType: "uint256", name: "_index", type: "uint256" }], name: "unstake", outputs: [], stateMutability: "nonpayable", type: "function" },
      { inputs: [], name: "unstakePenaltyDeposits", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
    ],
  },
};
